export const FORUM_CREATE = 'FORUM_CREATE'
export const FORUM_GET_ONE = 'FORUM_GET_ONE'
export const FORUM_GET_ALL = 'FORUM_GET_ALL'

export const FORUM_ADD_REPLY = 'FORUM_ADD_REPLY'
export const FORUM_TOGGLE_LIKE = 'FORUM_TOGGLE_LIKE'

export const FORUM_GET_TOTAL= 'FORUM_GET_TOTAL'

export const FORUM_APPROVE_REQUEST='FORUM_APPROVE_REQUEST'
export const FORUM_APPROVE_SUCCESS='FORUM_APPROVE_SUCCESS'
export const FORUM_APPROVE_FAIL='FORUM_APPROVE_FAIL'


export const FORUM_DELETE_REQUEST = 'FORUM_DELETE_REQUEST'
export const FORUM_DELETE_SUCCESS = 'FORUM_DELETE_SUCCESS'
export const FORUM_DELETE_FAIL = 'FORUM_DELETE_FAIL'