name: Build React App
on:
  push:
    branches: ['main']

jobs:
  heroku-custom-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: npm install & build
        working-directory: ./frontend
        run: |
          npm install
          CI=false npm run build 

      - name: Heroku login credentials
        run: |
          rm -rf .git
          git init
          sed -i -e "/frontend\/build/d" .gitignore
          cat > ~/.netrc <<EOF
            machine api.heroku.com
              login $HEROKU_EMAIL
              password $HEROKU_API_KEY
            machine git.heroku.com
              login $HEROKU_EMAIL
              password $HEROKU_API_KEY
          EOF
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
          HEROKU_EMAIL: ${{ secrets.HEROKU_EMAIL }}

      - name: Add Heroku remote
        run: heroku git:remote --app $HEROKU_APP_NAME
        env:
          HEROKU_APP_NAME: ${{ secrets.HEROKU_APP_NAME }}

      - name: Push to Heroku
        run: |
          git config user.email ${{ secrets.HEROKU_EMAIL }}
          git config user.name "Github"
          git add .
          git commit -m "deployment"
          git push -f heroku master